#Update all the sections by editing the data.yml file inside _data folder.

# Site Settings
title: My Resume
url: 'http://webjeda.com'
baseurl: '/pinnaclenetworking.github.io' #change it according to your repository name
description: A beautiful Jekyll theme for creating resume
# Style will be applied only after restarting the build or serve. Just choose one of the options.
theme_skin: blue # blue turquoise green berry orange ceramic
chrome_mobile_color: #use hex colors (ex:#1976d2) or leave empty if you don't want a color for chrome mobile searchbar

# Tracker
analytics: UA-22121129



# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed # http://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style

# Build settings
compress-site: yes

encoding: "utf-8"
compress_html: # - http://jch.penibelst.de/
  clippings: all
  ignore:
    envs: development

# Development Settings
port: 4000
host: 0.0.0.0
safe: false

github:
  username: pinnaclenetworking             # change to your github username

twitter:
  username: pinnaclenetwork            # change to your twitter username

instagram:
  username: pinnaclenetwork            # change to your instagram username

linkedin:
  username: in/ArtEppley

facebook:
  username: pinnaclenetworking2

youtube:
  username: channel/UC3TUpLCg1WQ2EUKDQiKWC2g

reddit:
  username: u/pinnaclenetwork

social:
  name: Art Eppley                  # it will shows as the copyright owner in Footer
  email: aeppley@pinnaclenetworking.com             # change to your email address
  phone: 518.844.9145
  links:
    # The first element serves as the copyright owner's link
    - https://twitter.com/pinnaclenetwork      # change to your twitter homepage
    - https://github.com/pinnaclenetworking       # change to your github homepage
    # Uncomment below to add more social links
    - https://www.facebook.com/pinnaclenetworking2
    - https://www.linkedin.com/in/ArtEppley